incrase serializer compatibility to django 1.8
i ran into this issue when using v2.4 with django v1.8. (i didn't previously read it isn't supported)
It's not in the release notes but django.db.model.Options many_to_many() now returns an ImmutableList which is really just a tuple with a bunch of warnings and hooks on it.

if we don't make this typecast change we get the following error

    TypeError: can only concatenate tuple (not "list") to tuple

I'm if this change is appropriate and not sure what, if any, additional tests to include with this .