Interactive doc: remove document.data.items from templates
"document_data_list" list of pairs is directly passed in template context,
so that we can use dictionaries with "items" as key (i.e.: data['items'])

Before this change, with the following Router config:

  api_router.register(r'items', ItemViewSet)

GET /docs/ failed with error:

  Internal Server Error: /docs/
    ...
    File "C:\Users\User\py-envs\ubiserver\lib\site-packages\django\template\defaulttags.py", line 200, in render
      .format(num_loopvars, len_item),
    ValueError: Need 2 values to unpack in for loop; got 4.

see https://docs.djangoproject.com/en/1.10/ref/templates/builtins/#for